<?php
require_once('../Commun/Identification.php');
require_once('../Commun/commun.php');
require_once('../Commun/constantes.php');
require_once('../Commun/ConnexionBD.php');

print("<head>");
print('<meta http-equiv="Content-Type" content="text/html; charset=cp1252" />');
print('<meta http-equiv="content-language" content="fr" /> ');
print('<meta name="viewport" content="width=device-width, initial-scale=1.0">');
print("<link href='../css/styles.css' type='text/css' rel='stylesheet'>");
print("<link href='../css/bootstrap.min.css' rel='stylesheet'>");
print("<script src='../js/jquery-min.js' type='text/javascript'></script>");
print("<script src='../js/bootstrap.min.js' type='text/javascript'></script>");
print('<title>Actes en vrac AGC: Philippe Nexon</title>');
print("</head>");

print("<body>");
print('<div class="container">');
//print("Vous etes authentifi&eacute; :-)<br>");

$connexionBD = ConnexionBD::singleton($gst_serveur_bd,$gst_utilisateur_bd,$gst_mdp_utilisateur_bd,$gst_nom_bd);
require_once("../Commun/menu.php");
$connexionBD->ferme();


?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">

<HTML>
<HEAD>
	
	<META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=windows-1252">
	<TITLE></TITLE>
	<META NAME="GENERATOR" CONTENT="LibreOffice 3.6  (Windows)">
	<META NAME="AUTHOR" CONTENT="Nadine Rominger">
	<META NAME="CREATED" CONTENT="20130918;14545987">
	<META NAME="CHANGEDBY" CONTENT="Nadine Rominger">
	<META NAME="CHANGED" CONTENT="20130924;17430694">
	
	<STYLE>
		<!-- 
		BODY,DIV,TABLE,THEAD,TBODY,TFOOT,TR,TH,TD,P { font-family:"Arial"; font-size:x-small }
		 -->
	</STYLE>
	
</HEAD>

<BODY TEXT="#000000">
<HR>
	<P><CENTER>
		<H1>R&eacute;sum&eacute;</H1>
		<A HREF="#table0">PM</A><BR>
		<A HREF="#table1">D&eacute;c&eacute;s</A><BR>
		<A HREF="#table2">Mariages</A><BR>
		
	</CENTER></P>
<HR>
<A NAME="table0"><H1>Feuille 1: <EM>PM</EM></H1></A>
<TABLE CELLSPACING="0" COLS="15" BORDER="0">
	<COLGROUP WIDTH="82"></COLGROUP>
	<COLGROUP WIDTH="124"></COLGROUP>
	<COLGROUP SPAN="8" WIDTH="86"></COLGROUP>
	<COLGROUP WIDTH="107"></COLGROUP>
	<COLGROUP SPAN="4" WIDTH="86"></COLGROUP>
	<TR>
		<TD HEIGHT="40" ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">ACTE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">DATE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">LIEU</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">NOM H </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">Prenom H</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">Lieu de Naissance</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">NOM F</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">PRENOM F</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">Lieu de Naissance </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">PERE H</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">MERE H</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">PERE F</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">MERE F</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">Observations</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">Source</TD>
	</TR>
	<TR>
		<TD HEIGHT="66" ALIGN="CENTER" VALIGN=MIDDLE>PM</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>15 Brumaire an VII (5/11/1798)</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABAND</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Guillaume</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Laprade 16180</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MOREAUD</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABAND Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LONGUEVILLE Anne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MOREAUD Pierre +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHRETIEN Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Il est cultivateur &agrave; moulin Neuf (Laprade)</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat vue 70 NMD 1793-1805</TD>
	</TR>
</TABLE>
<!-- ************************************************************************** -->
<HR>
<A NAME="table1"><H1>Feuille 2: <EM>D&eacute;c&eacute;s</EM></H1></A>
<TABLE CELLSPACING="0" COLS="15" BORDER="0">
	<COLGROUP WIDTH="60"></COLGROUP>
	<COLGROUP WIDTH="102"></COLGROUP>
	<COLGROUP SPAN="2" WIDTH="91"></COLGROUP>
	<COLGROUP SPAN="4" WIDTH="86"></COLGROUP>
	<COLGROUP WIDTH="96"></COLGROUP>
	<COLGROUP WIDTH="103"></COLGROUP>
	<COLGROUP SPAN="5" WIDTH="86"></COLGROUP>
	<TR>
		<TD HEIGHT="33" ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">ACTE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF" SDNUM="1036;0;JJ/MM/AAAA">DATE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">LIEU</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">NOM  </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">Prenom</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">Age</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">Lieu de Naissance</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">Profession</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">Epoux ou epouse</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">P&egrave;re </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">M&egrave;re </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">Reference</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF"><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF"><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF"> </TD>
	</TR>
	<TR>
		<TD HEIGHT="34" ALIGN="CENTER" VALIGN=MIDDLE>D</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-1978" SDNUM="1036;0;JJ/MM/AAAA">31/07/1894</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BITTARD</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>24 ans </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Romain 16347</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LETARD Nicolas</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BITTARD Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>D</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-23784" SDNUM="1036;0;JJ/MM/AAAA">17/11/1834</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABANT</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Barthelemy</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>75 ans </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Veuf de Jeanne Dubreuil</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
	</TR>
	<TR>
		<TD HEIGHT="35" ALIGN="CENTER" VALIGN=MIDDLE>D</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-8386" SDNUM="1036;0;JJ/MM/AAAA">13/01/1877</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABANT</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Rose</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>37 ans </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pillac 16260</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond Vue 1 D 1877</TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>D</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-23746" SDNUM="1036;0;JJ/MM/AAAA">25/12/1834</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Martial Viveyrol 24452</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DUVERGER</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>80 ans </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Natif de la charente </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Veuf de Marie BARDET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
	</TR>
	<TR>
		<TD HEIGHT="82" ALIGN="CENTER" VALIGN=MIDDLE>D</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-52898" SDNUM="1036;0;JJ/MM/AAAA">02/03/1755</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AA">St Vincent Jalmoutiers 24511</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LACHAIZE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Laurent</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>45 ans </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Martial en Angoumois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Scieur de long</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Vincent jalmoutiers Vue 178 BMS 1737-1792</TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>D</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-17958" SDNUM="1036;0;JJ/MM/AAAA">30/10/1850</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAMBERT</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>69 ans </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Juignac 16170</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Veuve de Pierre CHARIAUD</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAMBERT Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>ROI Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond Vue 10 D 1860</TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
	</TR>
	<TR>
		<TD HEIGHT="34" ALIGN="CENTER" VALIGN=MIDDLE>D</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-21976" SDNUM="1036;0;JJ/MM/AAAA">30/10/1839</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAVERGNE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>40 ans </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Laprade 16180</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHEVREUIL Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAVERGNE Jean +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BAUVAIX Fran&ccedil;oise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond Vue 8 D 1839</TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>D</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AAAA">2 frimaire An XII (24/11/1803)</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PALANCHIER</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Roufiac 16284</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Journali&egrave;re</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Veuve</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PALANCHIER Jacques</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>TROUBAT Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye Vue 8 D An XII</TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
	</TR>
</TABLE>
<!-- ************************************************************************** -->
<HR>
<A NAME="table2"><H1>Feuille 3: <EM>Mariages</EM></H1></A>
<TABLE CELLSPACING="0" COLS="15" BORDER="0">
	<COLGROUP WIDTH="61"></COLGROUP>
	<COLGROUP WIDTH="113"></COLGROUP>
	<COLGROUP WIDTH="86"></COLGROUP>
	<COLGROUP WIDTH="111"></COLGROUP>
	<COLGROUP SPAN="2" WIDTH="86"></COLGROUP>
	<COLGROUP WIDTH="123"></COLGROUP>
	<COLGROUP WIDTH="86"></COLGROUP>
	<COLGROUP WIDTH="96"></COLGROUP>
	<COLGROUP WIDTH="108"></COLGROUP>
	<COLGROUP WIDTH="118"></COLGROUP>
	<COLGROUP WIDTH="128"></COLGROUP>
	<COLGROUP WIDTH="103"></COLGROUP>
	<COLGROUP WIDTH="110"></COLGROUP>
	<COLGROUP WIDTH="86"></COLGROUP>
	<TR>
		<TD HEIGHT="33" ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">ACTE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF" SDNUM="1036;0;JJ/MM/AAAA">DATE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">LIEU</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">NOM  H</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">Prenom H</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">Origine H</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">NOM F </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">Prenom F</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">Origine F</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">P&egrave;re H</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">M&egrave;re H</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">P&egrave;re F</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">M&egrave;re F</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">Commentaires</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE BGCOLOR="#E6E6FF">References </TD>
	</TR>
	<TR>
		<TD HEIGHT="66" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-22678" SDNUM="1036;0;JJ/MM/AAAA">27/11/1837</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>AUBERT</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Riberac  24352</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PINDRAY</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>La Rochefoucauld 16281</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>AUBERT    Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHAUSSAI  Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PINDRAY Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAMBERT Marie Threrese</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Elle est n&eacute;e La Rochefoucaud 16 mais demeure Cumond</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond Vues 2 et 3 M 1837</TD>
	</TR>
	<TR>
		<TD HEIGHT="34" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-23111" SDNUM="1036;0;JJ/MM/AAAA">20/09/1836</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BAYONNE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Joseph</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Juignac 16170</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>COUSTILLAT</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Anne </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BAYONNE Pierre +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>FOUGERE  Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>COUSTILLAT Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DUBREUILH Anne +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat vue 9 M1836</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-74546" SDNUM="1036;0;JJ/MM/AAAA">23/11/1695</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BELAN</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Clement</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Les Essards 16130 </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GRAND</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye vue130 BMS 1692-1703</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-74387" SDNUM="1036;0;JJ/MM/AAAA">30/04/1696</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BERTHAUD</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;ois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Martial d'Aubeterre 16020</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CONDAMINE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE> Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye vue 134 BMS 1692-1703</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-52523" SDNUM="1036;0;JJ/MM/AAAA">11/03/1756</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BERTHOMET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Les Essards 16130 </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DESRUE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Catherine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SPP vue 392 BMS 1737-1792</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-75573" SDNUM="1036;0;JJ/MM/AAAA">30/01/1693</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BERTHOUMET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>De LESPINE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye vue 22 BMS 1692-1703</TD>
	</TR>
	<TR>
		<TD HEIGHT="66" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-78001" SDNUM="1036;0;JJ/MM/AAAA">08/06/1686</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BERTRAND</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BOUCHARD</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Catherine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond Vue 392 BMS1638-1701 </TD>
	</TR>
	<TR>
		<TD HEIGHT="34" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-32453" SDNUM="1036;0;JJ/MM/AAAA">22/02/1811</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BESSON </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Laprade 16180</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>ROUSSEAU</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BESSON     Jean +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>HERAUD Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAPEYRE Catherine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAPEYRE Catherine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>il a 26 ans et elle 28</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat vue 5 1811</TD>
	</TR>
	<TR>
		<TD HEIGHT="66" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AAAA">11 Messidor An II (19/06/1794)</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BLANCHARD </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GUILLOT</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BLANCHARD Jean +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DUPUY Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GUILLOT Joseph +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PERCHEVAL Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Il est n&eacute; Barbezieux et est ag&eacute; de 43 ans elle a 41 ans </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond  Vue3 M An II</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-33542" SDNUM="1036;0;JJ/MM/AAAA">29/02/1808</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BLANCHET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SIMONNET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Louise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Le Verdier &agrave; St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BLANCHET Fran&ccedil;ois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GROS     Catherine +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SIMONNET Fran&ccedil;ois + </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CABIROL  Michelle</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>il est cultivateur ag&eacute; de 28 ans et ele a 33 ans </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat vue 8 M 1808</TD>
	</TR>
	<TR>
		<TD HEIGHT="66" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-32819" SDNUM="1036;0;JJ/MM/AAAA">21/02/1810</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BLANCHET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BOUNAU</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BLANCHET Fran&ccedil;ois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GROS     Catherine +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BOUNAUD Fran&ccedil;ois +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MORAU Fran&ccedil;oise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Ce sont les parents epoux qui demeurent aux Essards 16</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat vue 3 M1810</TD>
	</TR>
	<TR>
		<TD HEIGHT="66" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-45550" SDNUM="1036;0;JJ/MM/AAAA">14/04/1775</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chassaignes 24114</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BOURGINON</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Clement</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>COURSELLE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Anne </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chassaignes 24114</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BOURGINON Guillaume</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GUILLEBERTAUX Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>COURSELLE Anne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Beaucoup de signatures</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chassaignes Vue 187 BMS 1737-1789</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AAAA">9 Messidor an VI (27/06/1798)</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BOURGUIGNON</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Guillaume</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>VILLARD</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Isabeau</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BOURGUIGNONClement</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>COURCELLE Anne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>VILLARD Jean +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABAND Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond vue 138 NMD 1793</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-42670" SDNUM="1036;0;JJ/MM/AAAA">03/03/1783</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BOURGUIGNON</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Etienne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Ragot &agrave; Laprade 16180</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>NAZAT</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Michelle</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE> Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond vue 461 BMS 1737-1792</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-22875" SDNUM="1036;0;JJ/MM/AAAA">14/05/1837</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BOURGUIGNON</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Laprade 16180</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PAQUET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BOURGUIGNON Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>COUPRIS    Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PAQUET Jean </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DUBREUILH Jeanne </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond vues 1 et 2 M 1837</TD>
	</TR>
	<TR>
		<TD HEIGHT="34" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-14354" SDNUM="1036;0;JJ/MM/AAAA">11/09/1860</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BRUN</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Antoine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bellon  16037</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABANT </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BRUN  Pierre +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>JOUSSIAUME Catherine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABAN Elie +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>JOUBERT Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond Vue 5 M 1860</TD>
	</TR>
	<TR>
		<TD HEIGHT="82" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-44501" SDNUM="1036;0;JJ/MM/AAAA">26/02/1778</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CABIROL</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Leonard</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BITTARD</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Il est natif de st Christophe en angoumois mais demeure depuis 6 ans &agrave; cumond </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CUMOND Vue 414 BMS1737-1792</TD>
	</TR>
	<TR>
		<TD HEIGHT="97" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AAAA">10 Ventose An X (01/03/1802)</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud 24118</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CADUSSEAU</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;ois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bessac&nbsp;? 16</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>COURCELLE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CADUSSEAU Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>VIRAR&nbsp;?      Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>COURCELLE Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DAGONET Anne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Il a 31 ans  n&eacute; Courlac , elle est ag&eacute;e de 21 ans n&eacute;e aux Essards demeure Chenaud</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud Vue 7 M An X</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-45609" SDNUM="1036;0;JJ/MM/AAAA">14/02/1775</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CADUSSEAUD</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Les Essards 16130 </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MONTAUDIE </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chadirat &agrave; St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="LEFT"><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SPP vue 301 BMS 1758-1792</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-31015" SDNUM="1036;0;JJ/MM/AAAA">30/01/1815</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CARMAGNAC </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;ois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Les Essards 16130 </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABAN</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;oise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CARMAGNAC Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>AUDOIN    Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABAN Antoine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>THOUBEIX Marie +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat vue 10 NMD 1815</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-45805" SDNUM="1036;0;JJ/MM/AAAA">02/08/1774</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABAN</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Romain 16347</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHASSAIN</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABAN Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BERTHAUD Fran&ccedil;oise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHASSAIN Fran&ccedil;ois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DAOUST Fran&ccedil;oise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SPP vue 295 BMS  1758-1792</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-19679" SDNUM="1036;0;JJ/MM/AAAA">12/02/1846</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABAN</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Quentin de Chalais 16346 </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DESROZIER</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABAN   Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAVERGNE Catherine </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DESROZIER Thomas </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PEYRONNAUD Anne </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>elle est n&eacute;e &agrave; Bazac 16</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye vues 3 et 4 M1846</TD>
	</TR>
	<TR>
		<TD HEIGHT="34" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-3721" SDNUM="1036;0;JJ/MM/AAAA">22/10/1889</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABANT</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Laprade 16180</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>ALLEMAGNE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Berthe</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABANT Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>VIRCHENAUD Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>ALLEMAGNE Jean </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DUBREUILH Fran&ccedil;oise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>l'epoux demeure &agrave; Angoul&ecirc;me </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat Vue 6 M 1889</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-56557" SDNUM="1036;0;JJ/MM/AAAA">23/02/1745</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHAIGNAUD</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Clement</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Tramonzac &agrave; Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>COURSELLE </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Elle est veuve de Jaques Lalanne </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SPP vue 201 BMS 1737-1792</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-17184" SDNUM="1036;0;JJ/MM/AAAA">12/12/1852</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHAIZE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Villetoureix 24586</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DEBENAS</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pillac 16260</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHAIZE Jean +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MATHIEUX Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DEBENAS Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DUPUY Fran&ccedil;oise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>elle demeure &agrave; Cumond 24</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond Vues7 et 8 M 1852</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-26365" SDNUM="1036;0;JJ/MM/AAAA">24/10/1827</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Lusignac 24247</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHAMOULAUD</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Louis</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Severin 16350</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DUVERGER</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Christine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Lusignac </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHAMOULAUD Jacques +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MOREAUD Marguerite +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DUVERGER Pierre </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>COURSIER Ren&eacute;e </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Lusignac vues 11 et 12 NMD 1829</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-60155" SDNUM="1036;0;JJ/MM/AAAA">19/04/1735</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHANAUD</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Louis</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>ETHIER</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond vue 743 BMS 1638-1701</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-47663" SDNUM="1036;0;JJ/MM/AAAA">01/07/1769</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHAUDRUT</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Le Fresse &agrave; Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DENOST </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Les Farges &agrave; St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SPP Photo 1769 5</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-51084" SDNUM="1036;0;JJ/MM/AAAA">18/02/1760</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHEVREUIL</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>NAZA</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>leonarde</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Jaque d'aubeterre 16020</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond vue 237</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-74977" SDNUM="1036;0;JJ/MM/AAAA">18/09/1694</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CLERIE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>de LAVERGNE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Ren&eacute;e</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye vue 103 BMS 1692-1703</TD>
	</TR>
	<TR>
		<TD HEIGHT="34" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-23040" SDNUM="1036;0;JJ/MM/AAAA">30/11/1836</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DALGER</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Blanzac 16/046</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GROS</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Anne Louise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DALGER Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DEBEAUD Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GROS Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GUILLEMLOT Marie +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat Vue 14 m 1836</TD>
	</TR>
	<TR>
		<TD HEIGHT="34" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-32315" SDNUM="1036;0;JJ/MM/AAAA">10/07/1811</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DAROYAT</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fouquebrune 16143</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PEYRONNET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Elizabeth</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DAROYAT Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LENOIR Alexandrine +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PEYRONNET Jean +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>il a 21 ans et elle 28</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat Vue 6 M 1811 </TD>
	</TR>
	<TR>
		<TD HEIGHT="66" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-39062" SDNUM="1036;0;JJ/MM/AAAA">17/01/1793</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DAUVERGNE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Laprade 16180</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>TERRADE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DAUVERGNE Fran&ccedil;ois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>HERIER Catherine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>TERRADE Leonard</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>FRUGIER Anne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Il est domestique de Labour ag&eacute; de 31 ans et elle a 22 ans </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond Vue 20 NMD1793-1798</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-31726" SDNUM="1036;0;JJ/MM/AAAA">18/02/1813</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DAVID</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Severin 16350</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>VILLEDARY  </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DAVID Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>VILLEDARY Fran&ccedil;ois +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>FOUGERON Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>il est veuf ag&eacute; de 32 ans elle a38 ans </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat Vue 5 M 1813</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-74612" SDNUM="1036;0;JJ/MM/AAAA">18/09/1695</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>de LAVERGNE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Les Essards 16130 </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>RAGANAU </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Catherine </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye vue 117 BMS 1692-1703</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-32737" SDNUM="1036;0;JJ/MM/AAAA">14/05/1810</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DELAGE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Laprade 16180</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GIRARD</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;oise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Antoine &agrave; St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DELAGE Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SAUDOUT Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GIRARD Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>NADAL Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Lui 26 ans et ele 28</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat Vue 10 M 1810 </TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-58053" SDNUM="1036;0;JJ/MM/AAAA">19/01/1741</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud 24118</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DEROUSIER</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>La Menecle</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BARIERE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud 24118</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud Vue 11 BMS 1740-1791</TD>
	</TR>
	<TR>
		<TD HEIGHT="66" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-58029" SDNUM="1036;0;JJ/MM/AAAA">12/02/1741</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud 24118</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DEROUSIER</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;ois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>La Menecle</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BOUSSATON</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud 24118</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud Vue 11 et 12 BMS 1740-1791</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-30681" SDNUM="1036;0;JJ/MM/AAAA">30/12/1815</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DERUE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CABIROL</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DERUE         Andr&eacute;</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BONTEMPS Anne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CABIROL Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GARD Catherine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St privat vue 47 NMD 1815</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-21999" SDNUM="1036;0;JJ/MM/AAAA">07/10/1839</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DUCHER</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;ois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Romain 16347</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAVERGNE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DUCHER Leonard +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DAMOUR    Marie +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAVERGNE Pierre +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GROS Isabeau +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat Vues 7 et 8 M 1839</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-43452" SDNUM="1036;0;JJ/MM/AAAA">10/01/1781</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DURANDEAU</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chez Tupat &agrave; Cumond</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>ROUBINET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond vue 1221BMS 1638-1701</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AAAA">23 fructidor an II (9/09/1794)</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DURY</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Charerie &agrave; Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DERUE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Catherine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Sac &agrave; St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DURI     Fran&ccedil;ois +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LORENT Antoinette</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DERUE Barthelemi +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>JOUBERT Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Il a 27 ans et elle 19</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat Vue 27 NMD 1793-1805</TD>
	</TR>
	<TR>
		<TD HEIGHT="66" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-41232" SDNUM="1036;0;JJ/MM/AAAA">08/02/1787</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Martial Viveyrol 24452</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DUVERGER</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bors en Angoumois 16052</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SARDET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Martial Viveyrol 24452</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DUVERGER Jean +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PEYTE Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SARDET Antoine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BOUTON Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Martial viveyrol  vue 45 BMS 1785-1792</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AAAA">13 Frmaire An III (3/12/1794)</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud 24118</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>ELION</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>FENIX</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;oise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Puivigier &agrave; Chenaud</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>ELION Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE> LAUCASSE Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>FENIX  Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LANET Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Il est laboureur ag&eacute; de 28 ans et elle a 23 ans </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud Vue 24 NMD 1793-</TD>
	</TR>
	<TR>
		<TD HEIGHT="66" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-44230" SDNUM="1036;0;JJ/MM/AAAA">24/11/1778</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>FAURE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Louis</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Laprade 16180</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SOULET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>La Coste &agrave; Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>FAURE  Estienne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DESROUSIERS  Marie +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SOULET Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>ROLLAND Elizabeth</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond Vue 418 BMS1737-1792</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-25520" SDNUM="1036;0;JJ/MM/AAAA">15/02/1830</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>FORGEREAUD </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Severin 16350</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BERTRAND</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>FORGEREAUD Thomas +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>OLIVIER Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BERTRAND Barthelemy</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>ANDRAUD Anne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond Vues 3 et 4 M1830</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-55874" SDNUM="1036;0;JJ/MM/AAAA">07/01/1747</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>FRICOT</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Thomas</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Martial d'Angouleme</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BOUFFENIE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye vue 126 BMS 1737-1792</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-55946" SDNUM="1036;0;JJ/MM/AAAA">27/10/1746</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Vincent jalmoutiers 24511</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LACOSTE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GUILLEBERTEAU</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Vincent Jalmoutiers 24511</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Vincent vue 80 BMS 1737-1792</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-72258" SDNUM="1036;0;JJ/MM/AAAA">28/02/1702</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LACOUR</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GUIMAUD&nbsp;? GUINARD&nbsp;?</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Peyronne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SPP vue 350  BMS 1633-1712</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-53372" SDNUM="1036;0;JJ/MM/AAAA">13/11/1753</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Petit Bersac  24323</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAVERGNE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Laprade 16180</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>NAZA</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>leonarde</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAVERGNE Fran&ccedil;ois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MARCHANT Margueite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>NAZA Joseph</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BOUNAU Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Petit Bersac vue 93 BMS 1737-1792</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-28793" SDNUM="1036;0;JJ/MM/AAAA">01/03/1821</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAVERGNE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Laprade 16180</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHEVREUIL</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAVERGNE Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BAUDET Michelle</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHEVREUIL Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>ROCHON Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond Vues 6 et 7 NMD 1821</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-32583" SDNUM="1036;0;JJ/MM/AAAA">15/10/1810</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LEONARDON</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Julien</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>ROCHON </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Elizabeth</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LEONARDON Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAJAUNIE Catherine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>ROCHON Jean +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>VILLATE Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Lui 26 ans et elle 28</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat vues 12 et 13 M 1810</TD>
	</TR>
	<TR>
		<TD HEIGHT="34" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-33485" SDNUM="1036;0;JJ/MM/AAAA">26/04/1808</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MAROIN</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;ois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Romain 16347</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MORILLON </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MAROIN Fran&ccedil;ois +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHANTRE Catherine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MORILLON Jean </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>JOULIN Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Il a 26 ans et ele 23</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat vue 8 M1808</TD>
	</TR>
	<TR>
		<TD HEIGHT="66" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDNUM="1036;0;JJ/MM/AAAA">15 Floreal an II (4/05/1794)</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MARSSAIN</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Romain 16347</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DUPEYRONT</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;oise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chez Bouchard &agrave; Cumond</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MARSSAIN    Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BEFFAGE Marguerire +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DUPEYRONT Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>TOURNIER Madeleine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Il est cultivateur ag&eacute;  43 ans et elle ag&eacute;e de 29 ans </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond Vue 28 NMD 1793-1798</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-25778" SDNUM="1036;0;JJ/MM/AAAA">02/06/1829</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MAY</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Leonard</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PASQUIS</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MAY Guillaume</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PARAGOLLES Anne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PAQUIS Leonard</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>VEDRENE Marie +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond vues 14 et 15 NMD 1829</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-74977" SDNUM="1036;0;JJ/MM/AAAA">18/09/1694</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MAZAU</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Arnaud</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CABIROL</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye vue 103 BMS 1692-1703</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-25520" SDNUM="1036;0;JJ/MM/AAAA">15/02/1830</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MILLAC</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Laprade 16180</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>ROCHON </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MILLAC Antoine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>TERRADE   Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>ROCHON Antoine +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHALESSE Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>il est n&eacute; Bonnes mais demeure Cumond </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond Vues 2 et 3 M 1830</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-61779" SDNUM="1036;0;JJ/MM/AAAA">07/11/1730</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud 24118</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MILLIET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;ois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bazac 16034</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>RENON</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud vue 550 BMS 1639-1739</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-59145" SDNUM="1036;0;JJ/MM/AAAA">23/01/1738</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MOGET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>EYNARD</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Antoinette </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>La Cussonie &agrave; Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond vue 12BMS 1737-1798 </TD>
	</TR>
	<TR>
		<TD HEIGHT="66" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-73565" SDNUM="1036;0;JJ/MM/AAAA">31/07/1698</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MONTAUDIE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Jacques d'Aubeterre 16020</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GUAR</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Catherine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>il est lab ag&eacute; de 35 ans elle servante ag&eacute;e de 30 ans</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye vue 155BMS 1692-1703</TD>
	</TR>
	<TR>
		<TD HEIGHT="34" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-47910" SDNUM="1036;0;JJ/MM/AAAA">27/10/1768</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>NADAL</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Laprade 16180</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PAVIOT</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>NADAL Daniel +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BERCEYX&nbsp;? Aim&eacute;</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PAVIOT Nicolas +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BENOIT</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SPP photo 1768 9</TD>
	</TR>
	<TR>
		<TD HEIGHT="34" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-51084" SDNUM="1036;0;JJ/MM/AAAA">18/02/1760</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>NAZA</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Louis</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St jaques d'aubeterre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHEVREUIL</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond vue 237</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-75327" SDNUM="1036;0;JJ/MM/AAAA">03/10/1693</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>OLIVIER</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;ois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Nabinaud 16240</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>FRAIGNAU</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Anne </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye vue 52 BMS 1692-1703</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-48533" SDNUM="1036;0;JJ/MM/AAAA">12/02/1767</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud 24118</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PARET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Louis</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>La Menescle</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GAILLARD </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;oise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>le Cluzeau &agrave; Chenaud 24118</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PARET Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LAURENT Elizabeth</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GAILLARD Pierre </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>FAURE Leonarde</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud vue 195 BMS 1740-1792</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-58425" SDNUM="1036;0;JJ/MM/AAAA">13/01/1740</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud 24118</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PAVIOT </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;ois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Courlac 16112</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BERNIER</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Louise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>il est tailleur d'habits</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud vue 4 BMS 1740-1792</TD>
	</TR>
	<TR>
		<TD HEIGHT="66" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-20902" SDNUM="1036;0;JJ/MM/AAAA">08/10/1842</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PHENIX</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;ois</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Quentin de Chalais 16346 </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>VILLEDARY</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PHENIX     Pierre </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>VINCENT   Louise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>VILLEDARY Barthelemy</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MORILLERE Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>parents epoux demeurent aux Essards et lui &agrave; Cumond </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat Vues 20 et 21 M 1842</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-32812" SDNUM="1036;0;JJ/MM/AAAA">28/02/1810</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PICHARDIE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Laprade 16180</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>VILLARD</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Antoine &agrave; St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>PICHARDIE Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>LERVOIRE&nbsp;? Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>VILARD Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>JACOUPIE Marie +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Lui 26 ans et elle 23</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat vue 5 M 1810</TD>
	</TR>
	<TR>
		<TD HEIGHT="34" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-33196" SDNUM="1036;0;JJ/MM/AAAA">09/02/1809</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490 </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>RAMBAUD</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Josephe</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Aubeterre 16020</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BARRIERE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>RAMBAUD  Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE> DUCHENE  Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BARRIERE Nicolas</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>GIRY  Elisabeth +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Il a 25 ans et elle 19</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat vue 5  M 1809</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-71836" SDNUM="1036;0;JJ/MM/AAAA">26/04/1703</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>REDEUILH</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Philippe</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Jean D'aubeterre 16020</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DENFER</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Double x </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye vue 195 BMS 1692-1703</TD>
	</TR>
	<TR>
		<TD HEIGHT="97" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-71836" SDNUM="1036;0;JJ/MM/AAAA">26/04/1703</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>REDEUILH</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Abraham</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Jean de Rouffiac  16284</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DENFER</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marie</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Il est chirurgien et fr&egrave;re de Philippe x le m&ecirc;me jour avec Marie Denfer s&oelig;ur</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye vue 195 BMS 1692-1703</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-74447" SDNUM="1036;0;JJ/MM/AAAA">01/03/1696</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye 24376</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SABATIER</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Antoine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MARILHAC</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Anne </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Aulaye vue 132 BMS 1692-1703</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-58706" SDNUM="1036;0;JJ/MM/AAAA">07/04/1739</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SOULET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Romain 16347</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>COURSELLE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Anne </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SPP vue 419 BMS 1713-1756</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-31555" SDNUM="1036;0;JJ/MM/AAAA">08/08/1813</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>TERRADE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jean</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Les Essards 16130 </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABAN</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat 24490</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>TERRADE Fran&ccedil;ois +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>BOUCHARD Fran&ccedil;oise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CHABAN Antoine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>THOUBEIX Marie +</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Privat vues 8 et 9 M 1813</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-23445" SDNUM="1036;0;JJ/MM/AAAA">22/10/1835</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>THERRADE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Leonard</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CARAILLE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Louise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>TERRADE Pierre </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>SIMONNET Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>CARAILLE Etienne </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>RENARD Marie </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Elle est veuve </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond  Vue 3 et 4 M 1835</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-48909" SDNUM="1036;0;JJ/MM/AAAA">01/02/1766</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud 24118</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>TOUBE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Bonnes 16049</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DESAGE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>TOUBE Laurent</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MOUNIE Catherine</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DESAGE Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MOUNIN Jeanne </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud vue 189 BMS 1710-1792</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-77512" SDNUM="1036;0;JJ/MM/AAAA">10/10/1687</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>TOUBEYX</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Pierre</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Nabinaud 16240</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>.UAU.&nbsp;?</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond 24368</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Cumond vue 405 BMS 1638-1701</TD>
	</TR>
	<TR>
		<TD HEIGHT="34" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-42238" SDNUM="1036;0;JJ/MM/AAAA">08/05/1784</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud 24118</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>TOUBEYX</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jacques</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Romain 16347</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>DUFOUR</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jeanne</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud 24118</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-68620" SDNUM="1036;0;JJ/MM/AAAA">14/02/1712</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Allemans 24007</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>VALLADE</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Jacques</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Seuvrin en angoumois 16350</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>NADAL</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Fran&ccedil;oise</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Allemans vue 124 BMS 1695-1717</TD>
	</TR>
	<TR>
		<TD HEIGHT="50" ALIGN="CENTER" VALIGN=MIDDLE>M</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE SDVAL="-55102" SDNUM="1036;0;JJ/MM/AAAA">17/02/1749</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud 24118</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>VINCENT</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Clement</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>St Quentin de Chalais 16346 </TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>MILIET</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Marguerite</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud 24118</TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE><BR></TD>
		<TD ALIGN="CENTER" VALIGN=MIDDLE>Chenaud vue 73 bMS 1740-1792 </TD>
	</TR>
</TABLE>
<!-- ************************************************************************** -->
</BODY>
</div>
</HTML>
